//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.Comments = new HashSet<Comments>();
        }
    
        public int RequestCode { get; set; }
        public string UserId { get; set; }
        public Nullable<int> TravelCode { get; set; }
        public string SourceAddress { get; set; }
        public string DestinationAddress { get; set; }
        public System.DateTime Date { get; set; }
        public string Frequency { get; set; }
        public string Summarry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual Travels Travels { get; set; }
        public virtual Users Users { get; set; }
    }
}
