//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsForUser
    {
        public string UserCode { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public int RequestsCode { get; set; }
    
        public virtual LocationTable LocationTable { get; set; }
        public virtual RequestsTable RequestsTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
