//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestsTable()
        {
            this.RequestsForUsers = new HashSet<RequestsForUser>();
            this.travel_discription_u = new HashSet<travel_discription_u>();
        }
    
        public int RequestsCode { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public Nullable<System.DateTime> RequestsDate { get; set; }
        public string Dedicated { get; set; }
        public string Frequency { get; set; }
    
        public virtual LocationTable LocationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsForUser> RequestsForUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<travel_discription_u> travel_discription_u { get; set; }
    }
}
