//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TravleTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TravleTable()
        {
            this.RouteTables = new HashSet<RouteTable>();
        }
    
        public int TravleCode { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<int> LocationCode { get; set; }
        public Nullable<System.DateTime> TravleDate { get; set; }
    
        public virtual EmployeeTable EmployeeTable { get; set; }
        public virtual LocationTable LocationTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteTable> RouteTables { get; set; }
    }
}
