//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class travel_discription_u
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public travel_discription_u()
        {
            this.travel_discription_u1 = new HashSet<travel_discription_u>();
        }
    
        public int id_travel_discription { get; set; }
        public Nullable<int> id_response_a { get; set; }
        public string usercode { get; set; }
        public int requestsCode { get; set; }
    
        public virtual RequestsTable RequestsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<travel_discription_u> travel_discription_u1 { get; set; }
        public virtual travel_discription_u travel_discription_u2 { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
